FROM mariadb:11.4

ENV MARIADB_ROOT_PASSWORD=4dm1n
ENV MARIADB_USER=admin
ENV MARIADB_PASSWORD=4dm1n
ENV MARIADB_DATABASE=edext

VOLUME ["/var/lib/mysql"]

COPY init/ /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/*.sh

EXPOSE 3306

CMD ["mariadbd"]
