package Presentacion;

import Logica.DTO.CursoResumen;
import Logica.DTO.DetalleProgramaFormacion;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class IFConsultaPrograma extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFConsultaPrograma
     */
    public IFConsultaPrograma() {
        initComponents();
        treeCursos.setModel(new DefaultTreeModel(null));
        cargarProgramas();
    }
        
    private void cargarProgramas(){
        IControlador icon = Fabrica.getInstance().getIControlador();
        List<String> nombres = icon.listarProgramas();
        cbProgramas.removeAllItems();
        for (String nombre:nombres){
            cbProgramas.addItem(nombre);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProgramas = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblFechaAlta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeCursos = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuarios1 = new javax.swing.JLabel();
        usersSeparator1 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(910, 910));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbProgramas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProgramas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbProgramas.addActionListener(this::cbProgramasActionPerformed);
        getContentPane().add(cbProgramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 390, 40));

        btnConsultar.setBackground(new java.awt.Color(35, 71, 75));
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 90, 40));

        lblDescripcion.setText("Descripcion");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 260, -1));

        lblFechaInicio.setText("Fecha Inicio");
        getContentPane().add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 260, -1));

        lblFechaFin.setText("Fecha Fin");
        getContentPane().add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 260, -1));

        lblFechaAlta.setText("Fecha Alta");
        getContentPane().add(lblFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 250, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 71, 75));
        jLabel1.setText("Descripcion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 71, 75));
        jLabel2.setText("Fecha Inicio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 71, 75));
        jLabel3.setText("Fecha Fin:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 71, 75));
        jLabel4.setText("Fecha Alta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel5.setText("Cursos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        jScrollPane2.setViewportView(treeCursos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 250, 490));

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/usuarios_white_32px.png"))); // NOI18N
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });

        lblUsuarios1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios1.setText("Crear Programa de Formacion");
        lblUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(755, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lblUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        usersSeparator1.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 390, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgramasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgramasActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String nombrePrograma = (String) cbProgramas.getSelectedItem();
        IControlador icon = Fabrica.getInstance().getIControlador();
        DetalleProgramaFormacion detalle = icon.consultarPrograma(nombrePrograma);
        
        if (detalle == null) return;
        
        lblDescripcion.setText(detalle.getDescripcion());
        lblFechaInicio.setText(detalle.getFechaInicio().toString());
        lblFechaFin.setText(detalle.getFechaFin().toString());
        lblFechaAlta.setText(detalle.getFechaAlta().toString());
        
        List<CursoResumen> cursos = detalle.getCursos();
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(detalle.getNombre());
        Map<String, List<CursoResumen>> porInstituto = new LinkedHashMap<>();
        for (CursoResumen curso : cursos){
            String instituto = curso.getNombreInstituto();
            //si no esta el instituto lo pongo como key nueva y le asocio la lista de cursos vacia
            if (!porInstituto.containsKey(instituto)){
                porInstituto.put(instituto, new ArrayList<>());
            }
            porInstituto.get(instituto).add(curso);
        }
        
        for (Map.Entry<String, List<CursoResumen>> entry : porInstituto.entrySet()){
            String nombreInstituto = entry.getKey();
            List<CursoResumen> cursosInstituto = entry.getValue();
            
            DefaultMutableTreeNode instiNode = new DefaultMutableTreeNode(nombreInstituto);
            for (CursoResumen curso: cursosInstituto){
                DefaultMutableTreeNode cursoNode = new DefaultMutableTreeNode(curso.getNombre());
                instiNode.add(cursoNode);
            }
            root.add(instiNode);
            
        }
        DefaultTreeModel arbol = new DefaultTreeModel(root);
        treeCursos.setModel(arbol);
        
        for (int i=0;i<treeCursos.getRowCount();i++){
            treeCursos.expandRow(i);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void lblConsultaProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaProgramaMouseClicked

    }//GEN-LAST:event_lblConsultaProgramaMouseClicked

    private void lblConsultaProgramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaProgramaMouseEntered

    }//GEN-LAST:event_lblConsultaProgramaMouseEntered

    private void lblConsultaProgramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaProgramaMouseExited

    }//GEN-LAST:event_lblConsultaProgramaMouseExited

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked

    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseEntered

    }//GEN-LAST:event_lblUsuariosMouseEntered

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited

    }//GEN-LAST:event_lblUsuariosMouseExited

    private void lblUsuarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseClicked

    private void lblUsuarios1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseEntered

    private void lblUsuarios1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cbProgramas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaAlta;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuarios1;
    private javax.swing.JTree treeCursos;
    private javax.swing.JSeparator usersSeparator1;
    // End of variables declaration//GEN-END:variables
}
