/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Usuario
 */
public class AltaCurso extends javax.swing.JDialog {

    /**
     * Creates new form AltaCurso
     */
    // Constructor para usarlo como JDialog modal desde JFMain
public AltaCurso(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
}


public AltaCurso() {
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbInstituto = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        spnDuracion = new javax.swing.JSpinner();
        spnHoras = new javax.swing.JSpinner();
        spnCreditos = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrevias = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setTitle("AltaCurso");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbInstituto.addActionListener(this::cbInstitutoActionPerformed);
        getContentPane().add(cbInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 19, 160, -1));

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 71, 130, -1));

        txtUrl.addActionListener(this::txtUrlActionPerformed);
        getContentPane().add(txtUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 100, 130, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 74, -1, -1));

        jLabel2.setText("URL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 103, -1, -1));

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 197, 290, 70));

        spnDuracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        getContentPane().add(spnDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 71, -1, -1));

        spnHoras.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        getContentPane().add(spnHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 100, -1, -1));

        spnCreditos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        getContentPane().add(spnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 131, -1, -1));

        lstPrevias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstPrevias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 130));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 320, -1, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 320, -1, -1));

        jLabel3.setText("Instituto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 22, -1, -1));

        jLabel4.setText("Duracion (meses)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 74, -1, -1));

        jLabel5.setText("Cantidad de Horas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 103, -1, -1));

        jLabel6.setText("Cantidad de Creditos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 134, -1, -1));

        jLabel7.setText("Previas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel8.setText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        txtFecha.addActionListener(this::txtFechaActionPerformed);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 131, 130, -1));

        jLabel9.setText("Fecha");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 134, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlActionPerformed

    private void cbInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInstitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInstitutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbInstituto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstPrevias;
    private javax.swing.JSpinner spnCreditos;
    private javax.swing.JSpinner spnDuracion;
    private javax.swing.JSpinner spnHoras;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
