/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Logica.Entidades.Instituto;
import Logica.Entidades.Curso;

/**
 *
 * @author Usuario
 */
public class AltaCurso extends javax.swing.JDialog {

    /**
     * Creates new form AltaCurso
     */

    public AltaCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtFecha.setText(LocalDate.now().format(formatter));

        cargarInstitutos();
        cargarCursosPrevias();

    }


    public AltaCurso() {
        initComponents();
    }

    private void cargarInstitutos() {
        try {
            IControlador icon = Fabrica.getInstance().getIControlador();
            List<Instituto> institutos = icon.listarInstitutos();

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Instituto inst : institutos) {
                model.addElement(inst.getNombre());
            }
            cbInstituto.setModel(model);
        } catch (Exception e) {
            System.err.println("Error al cargar institutos: " + e.getMessage());
        }
    }

    private void cargarCursosPrevias() {
        try {
            IControlador icon = Fabrica.getInstance().getIControlador();
            List<Curso> cursos = icon.listarCursos();

            DefaultListModel<String> model = new DefaultListModel<>();
            for (Curso c : cursos) {
                model.addElement(c.getNombre());
            }
            lstPrevias.setModel(model);
        } catch (Exception e) {
            System.err.println("Error al cargar cursos para previas: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbInstituto = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        spnDuracion = new javax.swing.JSpinner();
        spnHoras = new javax.swing.JSpinner();
        spnCreditos = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrevias = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setTitle("           AltaCurso");
        setMinimumSize(new java.awt.Dimension(620, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbInstituto.addActionListener(this::cbInstitutoActionPerformed);
        getContentPane().add(cbInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 160, -1));

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, -1));

        txtUrl.addActionListener(this::txtUrlActionPerformed);
        getContentPane().add(txtUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setText("URL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 290, 70));

        spnDuracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        getContentPane().add(spnDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 70, -1));

        spnHoras.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        getContentPane().add(spnHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, -1));

        spnCreditos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        getContentPane().add(spnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 70, -1));

        lstPrevias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstPrevias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 150, 130));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel3.setText("Instituto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel4.setText("Duracion (meses)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel5.setText("Cantidad de Horas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel6.setText("Cantidad de Creditos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel7.setText("Previas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel8.setText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtFecha.addActionListener(this::txtFechaActionPerformed);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        jLabel9.setText("Fecha");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtNombre.getText().trim().isEmpty() ||
                txtUrl.getText().trim().isEmpty() ||
                txtAreaDescripcion.getText().trim().isEmpty() ||
                txtFecha.getText().trim().isEmpty() ||
                cbInstituto.getSelectedIndex() == -1) {

            JOptionPane.showMessageDialog(
                    this, "Por favor, complete todos los campos obligatorios.",
                    "Campos Incompletos", JOptionPane.WARNING_MESSAGE
            );
            return;
        }


        LocalDate fechaAlta;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            fechaAlta = LocalDate.parse(txtFecha.getText().trim(), formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(
                    this, "El formato de fecha debe ser DD/MM/AAAA (ej. 18/08/2026).",
                    "Fecha Inválida", JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            IControlador icon = Fabrica.getInstance().getIControlador();
            String nombre = txtNombre.getText().trim();

            // 3. Validar existencia previa del curso Regla del CU
            if (icon.existeCurso(nombre)) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ya existe un curso registrado con el nombre '" + nombre + "'. Modifique el nombre antes de continuar.",
                        "Curso Duplicado",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            String url = txtUrl.getText().trim();
            String descripcion = txtAreaDescripcion.getText().trim();
            int duracion = (Integer) spnDuracion.getValue();
            int horas = (Integer) spnHoras.getValue();
            int creditos = (Integer) spnCreditos.getValue();


            String nombreInstituto = cbInstituto.getSelectedItem().toString();
            Instituto institutoSeleccionado = icon.listarInstitutos().stream()
                    .filter(inst -> inst.getNombre().equals(nombreInstituto))
                    .findFirst().orElse(null);

            if (institutoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un instituto válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }


            List<String> nombresPrevias = lstPrevias.getSelectedValuesList();
            List<Curso> previasSeleccionadas = icon.listarCursos().stream()
                    .filter(c -> nombresPrevias.contains(c.getNombre()))
                    .collect(java.util.stream.Collectors.toList());

            //Invocar alta en la lógica
            icon.altaCurso(nombre, descripcion, duracion, horas, creditos, url, fechaAlta, institutoSeleccionado, previasSeleccionadas);

            JOptionPane.showMessageDialog(this, "Curso registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el curso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlActionPerformed

    private void cbInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInstitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInstitutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbInstituto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstPrevias;
    private javax.swing.JSpinner spnCreditos;
    private javax.swing.JSpinner spnDuracion;
    private javax.swing.JSpinner spnHoras;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}