/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.Entidades.Curso;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;
import java.util.List;
import javax.swing.JOptionPane;

public class IFAgregarCursoAPrograma extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFAgregarCursoAPrograma
     */
    public IFAgregarCursoAPrograma() {
        initComponents();
        cargarProgramas();
        cargarCursos();
    }
    private void cargarProgramas(){
        IControlador icon = Fabrica.getInstance().getIControlador();
        List<String> nombres = icon.listarProgramas();
        cbProgramas.removeAllItems();
        for (String nombre:nombres){
            cbProgramas.addItem(nombre);
        }
    }
    private void cargarCursos(){
        IControlador icon = Fabrica.getInstance().getIControlador();
        List<Curso> cursos = icon.listarCursos();
        cbCursos.removeAllItems();
        for (Curso curso:cursos){
            cbCursos.addItem(curso.getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProgramas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbProgramas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProgramas.setMaximumSize(new java.awt.Dimension(72, 22));
        getContentPane().add(cbProgramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 87, 285, 34));

        jLabel1.setText("Programa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 65, -1, -1));

        jLabel2.setText("Curso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 146, -1, -1));

        cbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 280, 30));
        cbCursos.getAccessibleContext().setAccessibleName("");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 224, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombrePrograma = (String) cbProgramas.getSelectedItem();
        String nombreCurso = (String) cbCursos.getSelectedItem();
        
        if (nombrePrograma == null || nombreCurso == null){
            JOptionPane.showMessageDialog(this, "Seleccione un programa y un curso", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            IControlador icon = Fabrica.getInstance().getIControlador();
            icon.agregarCursoAPrograma(nombrePrograma, nombreCurso);
            JOptionPane.showMessageDialog(this, "Curso Agregado", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al agregar curso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void lblAgregarCursoProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarCursoProgramaMouseClicked

    }//GEN-LAST:event_lblAgregarCursoProgramaMouseClicked

    private void lblAgregarCursoProgramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarCursoProgramaMouseEntered

    }//GEN-LAST:event_lblAgregarCursoProgramaMouseEntered

    private void lblAgregarCursoProgramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarCursoProgramaMouseExited

    }//GEN-LAST:event_lblAgregarCursoProgramaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbCursos;
    private javax.swing.JComboBox<String> cbProgramas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
