package Presentacion;

import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

public class IFAltaPrograma extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFAltaPrograma
     */
    public IFAltaPrograma() {
        initComponents();
        setearSpinnersFecha();
    }
    
    private void setearSpinnersFecha() {
        LocalDate hoy = LocalDate.now();
        spDiaInicio.setModel(
                new javax.swing.SpinnerNumberModel(
                        hoy.getDayOfMonth(), 1, 31, 1
                )
        );
        spMesInicio.setModel(
                new javax.swing.SpinnerNumberModel(
                        hoy.getMonthValue(), 1, 12, 1
                )
        );
        spAnioInicio.setModel(
                new javax.swing.SpinnerNumberModel(
                        hoy.getYear(), hoy.getYear(), 2100, 1
                )
        );
        spDiaFin.setModel(
                new javax.swing.SpinnerNumberModel(
                        hoy.getDayOfMonth(), 1, 31, 1
                )
        );
        spMesFin.setModel(
                new javax.swing.SpinnerNumberModel(
                        hoy.getMonthValue(), 1, 12, 1
                )
        );
        spAnioFin.setModel(
                new javax.swing.SpinnerNumberModel(
                        hoy.getYear(), hoy.getYear(), 2100, 1
                )
        );

        // Mostrar el año sin separador
       spAnioInicio.setEditor(
               new JSpinner.NumberEditor(spAnioInicio, "0"));

       spAnioFin.setEditor(
               new JSpinner.NumberEditor(spAnioFin, "0"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuarios1 = new javax.swing.JLabel();
        usersSeparator1 = new javax.swing.JSeparator();
        usersSeparator2 = new javax.swing.JSeparator();
        spAnioFin = new javax.swing.JSpinner();
        spAnioInicio = new javax.swing.JSpinner();
        spDiaInicio = new javax.swing.JSpinner();
        spMesInicio = new javax.swing.JSpinner();
        spDiaFin = new javax.swing.JSpinner();
        spMesFin = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(910, 910));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 71, 75));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 71, 75));
        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 71, 75));
        jLabel3.setText("Fecha Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 71, 75));
        jLabel4.setText("Fecha Fin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 70, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 320, 30));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 320, 30));

        btnAceptar.setBackground(new java.awt.Color(35, 71, 75));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 100, 50));

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/usuarios_white_32px.png"))); // NOI18N
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });

        lblUsuarios1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios1.setText("Crear Programa de Formacion");
        lblUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(755, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lblUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        usersSeparator1.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 320, 10));

        usersSeparator2.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 320, 10));
        getContentPane().add(spAnioFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, 30));
        getContentPane().add(spAnioInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, 30));
        getContentPane().add(spDiaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, 30));
        getContentPane().add(spMesInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 30));
        getContentPane().add(spDiaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, 30));
        getContentPane().add(spMesFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        txtNombre.setForeground(new java.awt.Color(0,0,0));
        if(txtNombre.getText().equals("Ingrese nombre del programa")){
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMousePressed
        txtDescripcion.setForeground(new java.awt.Color(0,0,0));
        if(txtDescripcion.getText().equals("Ingrese descripcion")){
            txtDescripcion.setText("");
        }
    }//GEN-LAST:event_txtDescripcionMousePressed
/*
    private void txtFInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFInicioMousePressed
        txtFInicio.setForeground(new java.awt.Color(0,0,0));
        if(txtFInicio.getText().equals("dd/mm/aaaa")){
            txtFInicio.setText("");
        }
    }//GEN-LAST:event_txtFInicioMousePressed

    private void txtFFinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFFinMousePressed
        txtFFin.setForeground(new java.awt.Color(0,0,0));
        if(txtFFin.getText().equals("dd/mm/aaaa")){
            txtFFin.setText("");
        }
    }//GEN-LAST:event_txtFFinMousePressed
*/
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtNombre.getText().trim().isEmpty() || txtNombre.getText().equals("Ingrese nombre del programa") || txtDescripcion.getText().trim().isEmpty() || txtDescripcion.getText().equals("Ingrese descripcion")){
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        LocalDate fechaInicio;
        LocalDate fechaFin;

        try {
            int diaInicio = (Integer) spDiaInicio.getValue();
            int mesInicio = (Integer) spMesInicio.getValue();
            int anioInicio = (Integer) spAnioInicio.getValue();

            fechaInicio = LocalDate.of(
                    anioInicio,
                    mesInicio,
                    diaInicio
            );

            int diaFin = (Integer) spDiaFin.getValue();
            int mesFin = (Integer) spMesFin.getValue();
            int anioFin = (Integer) spAnioFin.getValue();

            fechaFin = LocalDate.of(
                    anioFin,
                    mesFin,
                    diaFin
            );
        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "La fecha ingresada no es válida.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        return;
        }

        // Fecha de fin anterior o igual a fecha de inicio
        if (fechaFin.isBefore(fechaInicio)) {
            JOptionPane.showMessageDialog(
                    this,
                    "La fecha de fin no puede ser anterior a la fecha de inicio.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        
        try{
            IControlador icon = Fabrica.getInstance().getIControlador();
            String nombre = txtNombre.getText().trim();
            String descripcion = txtDescripcion.getText().trim();
            
            if (icon.existePrograma(nombre)){
               JOptionPane.showMessageDialog(this, "Ya existe un programa con el nombre '" + nombre + "'.", "Programa Duplicado", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            icon.altaPrograma(nombre, descripcion, fechaInicio, fechaFin, LocalDate.now());
            JOptionPane.showMessageDialog(this, "Programa de Formacion creado", "Exito", JOptionPane.INFORMATION_MESSAGE);
           
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al guardar el programa: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void lblAltaProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaProgramaMouseClicked

    }//GEN-LAST:event_lblAltaProgramaMouseClicked

    private void lblAltaProgramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaProgramaMouseEntered

    }//GEN-LAST:event_lblAltaProgramaMouseEntered

    private void lblAltaProgramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaProgramaMouseExited

    }//GEN-LAST:event_lblAltaProgramaMouseExited

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked

    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseEntered

    }//GEN-LAST:event_lblUsuariosMouseEntered

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited

    }//GEN-LAST:event_lblUsuariosMouseExited

    private void lblUsuarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseClicked

    private void lblUsuarios1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseEntered

    private void lblUsuarios1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuarios1;
    private javax.swing.JSpinner spAnioFin;
    private javax.swing.JSpinner spAnioInicio;
    private javax.swing.JSpinner spDiaFin;
    private javax.swing.JSpinner spDiaInicio;
    private javax.swing.JSpinner spMesFin;
    private javax.swing.JSpinner spMesInicio;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JSeparator usersSeparator1;
    private javax.swing.JSeparator usersSeparator2;
    // End of variables declaration//GEN-END:variables
}
