/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author samio
 */
public class IFAltaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFAltaUsuario
     */
    public IFAltaUsuario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuarios1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usersSeparator = new javax.swing.JSeparator();
        lblUsuarios2 = new javax.swing.JLabel();
        usersSeparator1 = new javax.swing.JSeparator();
        lblUsuarios3 = new javax.swing.JLabel();
        usersSeparator2 = new javax.swing.JSeparator();
        lblUsuarios4 = new javax.swing.JLabel();
        usersSeparator3 = new javax.swing.JSeparator();
        lblUsuarios5 = new javax.swing.JLabel();
        usersSeparator4 = new javax.swing.JSeparator();
        lblUsuarios6 = new javax.swing.JLabel();
        lblUsuarios7 = new javax.swing.JLabel();
        usersSeparator5 = new javax.swing.JSeparator();
        lblUsuarios8 = new javax.swing.JLabel();
        usersSeparator6 = new javax.swing.JSeparator();
        lblUsuarios9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/usuarios_white_32px.png"))); // NOI18N
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });

        lblUsuarios1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios1.setText("Alta usuario");
        lblUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 579, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        usersSeparator.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, 10));

        lblUsuarios2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios2.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios2.setText("ingrese nickname de usuario");
        lblUsuarios2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios2MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 38));

        usersSeparator1.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 10));

        lblUsuarios3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios3.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios3.setText("ingrese nombre de usuario");
        lblUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios3MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 38));

        usersSeparator2.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, 10));

        lblUsuarios4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios4.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios4.setText("ingrese apellido de usuario");
        lblUsuarios4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios4MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 38));

        usersSeparator3.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 270, 10));

        lblUsuarios5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios5.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios5.setText("ingrese nickname de usuario");
        lblUsuarios5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios5MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 38));

        usersSeparator4.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 40, 10));

        lblUsuarios6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios6.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios6.setText("dia");
        lblUsuarios6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios6MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, 38));

        lblUsuarios7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios7.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios7.setText("Fecha de nacimiento");
        lblUsuarios7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios7MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 200, 38));

        usersSeparator5.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 40, 10));

        lblUsuarios8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios8.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios8.setText("mes");
        lblUsuarios8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios8MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 40, 38));

        usersSeparator6.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 70, 10));

        lblUsuarios9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios9.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios9.setText("año");
        lblUsuarios9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuarios9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios9MouseExited(evt);
            }
        });
        getContentPane().add(lblUsuarios9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 50, 38));

        jCheckBox1.setText("Alumno");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jCheckBox2.setText("Docente");
        jCheckBox2.addActionListener(this::jCheckBox2ActionPerformed);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jButton1.setText("Aceptar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked

    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseEntered

    }//GEN-LAST:event_lblUsuariosMouseEntered

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited

    }//GEN-LAST:event_lblUsuariosMouseExited

    private void lblUsuarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseClicked

    private void lblUsuarios1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseEntered

    private void lblUsuarios1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseExited

    private void lblUsuarios2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios2MouseClicked
   
    }//GEN-LAST:event_lblUsuarios2MouseClicked

    private void lblUsuarios2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios2MouseEntered
    
    }//GEN-LAST:event_lblUsuarios2MouseEntered

    private void lblUsuarios2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios2MouseExited
 
    }//GEN-LAST:event_lblUsuarios2MouseExited

    private void lblUsuarios3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios3MouseClicked

    private void lblUsuarios3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios3MouseEntered

    private void lblUsuarios3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios3MouseExited

    private void lblUsuarios4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios4MouseClicked

    private void lblUsuarios4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios4MouseEntered

    private void lblUsuarios4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios4MouseExited

    private void lblUsuarios5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios5MouseClicked

    private void lblUsuarios5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios5MouseEntered

    private void lblUsuarios5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios5MouseExited

    private void lblUsuarios6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios6MouseClicked

    private void lblUsuarios6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios6MouseEntered

    private void lblUsuarios6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios6MouseExited

    private void lblUsuarios7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios7MouseClicked

    private void lblUsuarios7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios7MouseEntered

    private void lblUsuarios7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios7MouseExited

    private void lblUsuarios8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios8MouseClicked

    private void lblUsuarios8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios8MouseEntered

    private void lblUsuarios8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios8MouseExited

    private void lblUsuarios9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios9MouseClicked

    private void lblUsuarios9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios9MouseEntered

    private void lblUsuarios9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios9MouseExited

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuarios1;
    private javax.swing.JLabel lblUsuarios2;
    private javax.swing.JLabel lblUsuarios3;
    private javax.swing.JLabel lblUsuarios4;
    private javax.swing.JLabel lblUsuarios5;
    private javax.swing.JLabel lblUsuarios6;
    private javax.swing.JLabel lblUsuarios7;
    private javax.swing.JLabel lblUsuarios8;
    private javax.swing.JLabel lblUsuarios9;
    private javax.swing.JSeparator usersSeparator;
    private javax.swing.JSeparator usersSeparator1;
    private javax.swing.JSeparator usersSeparator2;
    private javax.swing.JSeparator usersSeparator3;
    private javax.swing.JSeparator usersSeparator4;
    private javax.swing.JSeparator usersSeparator5;
    private javax.swing.JSeparator usersSeparator6;
    // End of variables declaration//GEN-END:variables
}
