/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Logica.Entidades.Instituto;
import Logica.Entidades.Curso;
/**
 *
 * @author Usuario
 */
public class IFAltaCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFAltaCurso
     */
    public IFAltaCurso() {
        initComponents();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtFecha.setText(LocalDate.now().format(formatter));
        
        cargarInstitutos();
        cargarPrevias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbInstituto = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        spnDuracion = new javax.swing.JSpinner();
        spnHoras = new javax.swing.JSpinner();
        spnCreditos = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrevias = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        cbInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbInstituto.addActionListener(this::cbInstitutoActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtUrl.addActionListener(this::txtUrlActionPerformed);

        jLabel1.setText("Nombre");

        jLabel2.setText("URL");

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        spnDuracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));

        spnHoras.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spnCreditos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        lstPrevias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstPrevias);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel3.setText("Instituto");

        jLabel4.setText("Duracion (meses)");

        jLabel5.setText("Cantidad de Horas");

        jLabel6.setText("Cantidad de Creditos");

        jLabel7.setText("Previas");

        jLabel8.setText("Descripcion");

        txtFecha.addActionListener(this::txtFechaActionPerformed);

        jLabel9.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 47, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(jLabel3)
                            .addGap(16, 16, 16)
                            .addComponent(cbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(spnDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2)
                            .addGap(49, 49, 49)
                            .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(jLabel5)
                            .addGap(22, 22, 22)
                            .addComponent(spnHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel9)
                            .addGap(39, 39, 39)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(jLabel6)
                            .addGap(19, 19, 19)
                            .addComponent(spnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(490, 490, 490)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(btnCancelar)
                                    .addGap(104, 104, 104)
                                    .addComponent(btnAceptar)))
                            .addGap(40, 40, 40)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 48, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(cbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(spnDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(spnHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(spnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7)
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCancelar)
                                .addComponent(btnAceptar)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 38, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInstitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInstitutoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlActionPerformed

    private void cargarInstitutos() {
        try {
            IControlador icon = Fabrica.getInstance().getIControlador();
            List<Instituto> institutos = icon.listarInstitutos();

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Instituto inst : institutos) {
                model.addElement(inst.getNombre());
            }
            cbInstituto.setModel(model);
       }catch (Exception e) {
        System.err.println("Error al cargar institutos: " + e.getMessage());
    }
}

private void cargarPrevias() {
    try {
        IControlador icon = Fabrica.getInstance().getIControlador();
        List<Curso> cursos = icon.listarCursos();

        DefaultListModel<String> model = new DefaultListModel<>();
        for (Curso c : cursos) {
            model.addElement(c.getNombre());
        }
        lstPrevias.setModel(model);
    } catch (Exception e) {
        System.err.println("Error al cargar cursos para previas: " + e.getMessage());
    }
}

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtNombre.getText().trim().isEmpty() ||
            txtUrl.getText().trim().isEmpty() ||
            txtAreaDescripcion.getText().trim().isEmpty() ||
            txtFecha.getText().trim().isEmpty() ||
            cbInstituto.getSelectedIndex() == -1) {

            JOptionPane.showMessageDialog(
                this, "Por favor, complete todos los campos obligatorios.",
                "Campos Incompletos", JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        LocalDate fechaAlta;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            fechaAlta = LocalDate.parse(txtFecha.getText().trim(), formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(
                this, "El formato de fecha debe ser DD/MM/AAAA (ej. 18/08/2026).",
                "Fecha Inválida", JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            IControlador icon = Fabrica.getInstance().getIControlador();
            String nombre = txtNombre.getText().trim();

            // 3. Validar existencia previa del curso Regla del CU
            if (icon.existeCurso(nombre)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un curso registrado con el nombre '" + nombre + "'. Modifique el nombre antes de continuar.",
                    "Curso Duplicado",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            String url = txtUrl.getText().trim();
            String descripcion = txtAreaDescripcion.getText().trim();
            int duracion = (Integer) spnDuracion.getValue();
            int horas = (Integer) spnHoras.getValue();
            int creditos = (Integer) spnCreditos.getValue();

            String nombreInstituto = cbInstituto.getSelectedItem().toString();
            Instituto institutoSeleccionado = icon.listarInstitutos().stream()
            .filter(inst -> inst.getNombre().equals(nombreInstituto))
            .findFirst().orElse(null);

            if (institutoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un instituto válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            List<String> nombresPrevias = lstPrevias.getSelectedValuesList();
            List<Curso> previasSeleccionadas = icon.listarCursos().stream()
            .filter(c -> nombresPrevias.contains(c.getNombre()))
            .collect(java.util.stream.Collectors.toList());

            //Invocar alta en la lógica
            icon.altaCurso(nombre, descripcion, duracion, horas, creditos, url, fechaAlta, institutoSeleccionado, previasSeleccionadas);

            JOptionPane.showMessageDialog(this, "Curso registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el curso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbInstituto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstPrevias;
    private javax.swing.JSpinner spnCreditos;
    private javax.swing.JSpinner spnDuracion;
    private javax.swing.JSpinner spnHoras;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
