/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Usuario
 */
public class IFAltaInstituto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFAltaInstituto
     */
    public IFAltaInstituto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAltaInstituto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreInstituto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Nombre del Instituto");

        txtNombreInstituto.setBackground(new java.awt.Color(242, 242, 242));
        txtNombreInstituto.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreInstituto.setText("Ingrese nombre del instituto");
        txtNombreInstituto.setBorder(null);
        txtNombreInstituto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreInstitutoMousePressed(evt);
            }
        });
        txtNombreInstituto.addActionListener(this::txtNombreInstitutoActionPerformed);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblAltaInstituto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAltaInstituto.setForeground(new java.awt.Color(255, 255, 255));
        lblAltaInstituto.setText("Alta de Instituto");
        lblAltaInstituto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAltaInstitutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAltaInstitutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAltaInstitutoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltaInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltaInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreInstitutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreInstitutoMousePressed
        txtNombreInstituto.setForeground(new java.awt.Color(0,0,0));
        if(txtNombreInstituto.getText().equals("Ingrese nombre del instituto")){
            txtNombreInstituto.setText("");
        }
    }//GEN-LAST:event_txtNombreInstitutoMousePressed

    private void txtNombreInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreInstitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreInstitutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); // Cierra la ventana
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblAltaInstitutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaInstitutoMouseClicked

    }//GEN-LAST:event_lblAltaInstitutoMouseClicked

    private void lblAltaInstitutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaInstitutoMouseEntered

    }//GEN-LAST:event_lblAltaInstitutoMouseEntered

    private void lblAltaInstitutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAltaInstitutoMouseExited

    }//GEN-LAST:event_lblAltaInstitutoMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = txtNombreInstituto.getText().trim();
        if (nombre.isEmpty() || nombre.equals("Ingrese nombre del instituto")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Debe ingresar el nombre del instituto.",
                "Campo Requerido",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Logica.controladores.IControlador icon =
        Logica.controladores.Fabrica.getInstance().getIControlador();

        // Validar nombre único (regla del CU)
        if (icon.existeInstituto(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ya existe un instituto con ese nombre. Modifique el nombre o cancele.",
                "Instituto existente",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; //
        }

        try {
            icon.altaInstituto(nombre);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Instituto registrado correctamente.");
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ocurrió un error al registrar el instituto: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAltaInstituto;
    private javax.swing.JTextField txtNombreInstituto;
    // End of variables declaration//GEN-END:variables
}
