/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.DTO.DetalleUsuario;
import Logica.DTO.UsuarioResumen;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class IFConsultaUsuario extends javax.swing.JInternalFrame {


    private List<UsuarioResumen> usuariosCache = new ArrayList<>();


    public IFConsultaUsuario() {
        initComponents();
        cargarUsuarios();
    }

    

    private void cargarUsuarios() {
        IControlador ic = Fabrica.getInstance().getIControlador();
        usuariosCache = ic.listarUsuarios();

        DefaultListModel<String> model = new DefaultListModel<>();
        for (UsuarioResumen u : usuariosCache) {
            model.addElement(u.toString());
        }
        lstUsuarios.setModel(model);
        txtDetalle.setText("Seleccione un usuario de la lista para ver su información.");
    }

    /**
     * Arma el texto de detalle a partir del DTO devuelto por el controlador.
     */
    private String formatearDetalle(DetalleUsuario detalle) {
        StringBuilder sb = new StringBuilder();
        sb.append("Nickname: ").append(detalle.getNickname()).append("\n");
        sb.append("Nombre: ").append(detalle.getNombre()).append(" ").append(detalle.getApellido()).append("\n");
        sb.append("Correo electrónico: ").append(detalle.getEmail()).append("\n");
        sb.append("Fecha de nacimiento: ").append(detalle.getFechaNacimiento()).append("\n");
        sb.append("Tipo de usuario: ").append(detalle.getTipoUsuario()).append("\n");

        if ("Docente".equals(detalle.getTipoUsuario())) {
            sb.append("Instituto: ").append(detalle.getInstituto()).append("\n");

            sb.append("\nCursos registrados:\n");
            agregarListado(sb, detalle.getCursos());

            sb.append("\nEdiciones de cursos registradas:\n");
            agregarListado(sb, detalle.getEdiciones());

            sb.append("\nProgramas de formación registrados:\n");
            agregarListado(sb, detalle.getProgramas());

        } else {
            sb.append("\nEdiciones de cursos en las que se inscribió:\n");
            agregarListado(sb, detalle.getEdiciones());

            sb.append("\nProgramas de formación en los que se inscribió:\n");
            agregarListado(sb, detalle.getProgramas());
        }

        return sb.toString();
    }

    private void agregarListado(StringBuilder sb, List<String> items) {
        if (items == null || items.isEmpty()) {
            sb.append("  (sin registros)\n");
            return;
        }
        for (String item : items) {
            sb.append("  - ").append(item).append("\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        lblUsuarios1 = new javax.swing.JLabel();
        lblListaUsuarios = new javax.swing.JLabel();
        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList<>();
        lblDetalleUsuario = new javax.swing.JLabel();
        jScrollPaneDetalle = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();

        setBorder(null);
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(910, 640));
        setPreferredSize(new java.awt.Dimension(910, 700));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(206, 206, 206));
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/usuarios_white_32px.png"))); // NOI18N
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });

        lblUsuarios1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuarios1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios1.setText("Consulta de usuario");
        lblUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarios1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(669, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        lblListaUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListaUsuarios.setForeground(new java.awt.Color(35, 71, 75));
        lblListaUsuarios.setText("Usuarios registrados");
        getContentPane().add(lblListaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 280, 25));

        lstUsuarios.addListSelectionListener(this::lstUsuariosValueChanged);
        jScrollPaneUsuarios.setViewportView(lstUsuarios);

        getContentPane().add(jScrollPaneUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 280));

        lblDetalleUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetalleUsuario.setForeground(new java.awt.Color(35, 71, 75));
        lblDetalleUsuario.setText("Detalle del usuario");
        getContentPane().add(lblDetalleUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 65, 530, 25));

        txtDetalle.setEditable(false);
        txtDetalle.setColumns(20);
        txtDetalle.setLineWrap(true);
        txtDetalle.setRows(5);
        txtDetalle.setText("Seleccione un usuario de la lista para ver su información.");
        txtDetalle.setWrapStyleWord(true);
        jScrollPaneDetalle.setViewportView(txtDetalle);

        getContentPane().add(jScrollPaneDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 520, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked

    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseEntered

    }//GEN-LAST:event_lblUsuariosMouseEntered

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited

    }//GEN-LAST:event_lblUsuariosMouseExited

    private void lblUsuarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseClicked

    private void lblUsuarios1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseEntered

    private void lblUsuarios1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarios1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarios1MouseExited

    private void lstUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsuariosValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        int index = lstUsuarios.getSelectedIndex();
        if (index < 0 || index >= usuariosCache.size()) {
            txtDetalle.setText("Seleccione un usuario de la lista para ver su información.");
            return;
        }

        String nickname = usuariosCache.get(index).getNickname();
        IControlador ic = Fabrica.getInstance().getIControlador();

        try {
            DetalleUsuario detalle = ic.consultarUsuario(nickname);
            if (detalle == null) {
                txtDetalle.setText("No se encontró información para el usuario seleccionado.");
                return;
            }
            txtDetalle.setText(formatearDetalle(detalle));
            txtDetalle.setCaretPosition(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
            this, "Ocurrió un error al consultar el usuario: " + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_lstUsuariosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneDetalle;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    private javax.swing.JLabel lblDetalleUsuario;
    private javax.swing.JLabel lblListaUsuarios;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblUsuarios1;
    private javax.swing.JList<String> lstUsuarios;
    private javax.swing.JTextArea txtDetalle;
    // End of variables declaration//GEN-END:variables
}
