package Presentacion;

import Logica.DTO.CursoResumen;
import Logica.DTO.DetalleProgramaFormacion;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class IFConsultaPrograma extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFConsultaPrograma
     */
    public IFConsultaPrograma() {
        initComponents();
        treeCursos.setModel(new DefaultTreeModel(null));
        cargarProgramas();
    }
        
    private void cargarProgramas(){
        IControlador icon = Fabrica.getInstance().getIControlador();
        List<String> nombres = icon.listarProgramas();
        cbProgramas.removeAllItems();
        for (String nombre:nombres){
            cbProgramas.addItem(nombre);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblConsultaPrograma = new javax.swing.JLabel();
        cbProgramas = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblFechaAlta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeCursos = new javax.swing.JTree();

        cbProgramas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProgramas.addActionListener(this::cbProgramasActionPerformed);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        lblDescripcion.setText("Descripcion");

        lblFechaInicio.setText("Fecha Inicio");

        lblFechaFin.setText("Fecha Fin");

        lblFechaAlta.setText("Fecha Alta");

        jLabel1.setText("Descripcion:");

        jLabel2.setText("Fecha Inicio:");

        jLabel3.setText("Fecha Fin:");

        jLabel4.setText("Fecha Alta:");

        jLabel5.setText("Cursos:");

        jScrollPane2.setViewportView(treeCursos);

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblConsultaPrograma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConsultaPrograma.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultaPrograma.setText("Consulta de Programa");
        lblConsultaPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultaProgramaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsultaProgramaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsultaProgramaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultaPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnConsultar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFechaAlta))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaInicio)
                                    .addComponent(lblDescripcion)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFechaFin)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaInicio)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaFin)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaAlta)
                            .addComponent(jLabel4))
                        .addGap(0, 328, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgramasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgramasActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String nombrePrograma = (String) cbProgramas.getSelectedItem();
        IControlador icon = Fabrica.getInstance().getIControlador();
        DetalleProgramaFormacion detalle = icon.consultarPrograma(nombrePrograma);
        
        if (detalle == null) return;
        
        lblDescripcion.setText(detalle.getDescripcion());
        lblFechaInicio.setText(detalle.getFechaInicio().toString());
        lblFechaFin.setText(detalle.getFechaFin().toString());
        lblFechaAlta.setText(detalle.getFechaAlta().toString());
        
        List<CursoResumen> cursos = detalle.getCursos();
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(detalle.getNombre());
        Map<String, List<CursoResumen>> porInstituto = new LinkedHashMap<>();
        for (CursoResumen curso : cursos){
            String instituto = curso.getNombreInstituto();
            //si no esta el instituto lo pongo como key nueva y le asocio la lista de cursos vacia
            if (!porInstituto.containsKey(instituto)){
                porInstituto.put(instituto, new ArrayList<>());
            }
            porInstituto.get(instituto).add(curso);
        }
        
        for (Map.Entry<String, List<CursoResumen>> entry : porInstituto.entrySet()){
            String nombreInstituto = entry.getKey();
            List<CursoResumen> cursosInstituto = entry.getValue();
            
            DefaultMutableTreeNode instiNode = new DefaultMutableTreeNode(nombreInstituto);
            for (CursoResumen curso: cursosInstituto){
                DefaultMutableTreeNode cursoNode = new DefaultMutableTreeNode(curso.getNombre());
                instiNode.add(cursoNode);
            }
            root.add(instiNode);
            
        }
        DefaultTreeModel arbol = new DefaultTreeModel(root);
        treeCursos.setModel(arbol);
        
        for (int i=0;i<treeCursos.getRowCount();i++){
            treeCursos.expandRow(i);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void lblConsultaProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaProgramaMouseClicked

    }//GEN-LAST:event_lblConsultaProgramaMouseClicked

    private void lblConsultaProgramaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaProgramaMouseEntered

    }//GEN-LAST:event_lblConsultaProgramaMouseEntered

    private void lblConsultaProgramaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaProgramaMouseExited

    }//GEN-LAST:event_lblConsultaProgramaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cbProgramas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConsultaPrograma;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaAlta;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JTree treeCursos;
    // End of variables declaration//GEN-END:variables
}
