/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.DTO.DetalleEdicionCurso;
import Logica.Entidades.Curso;
import Logica.Entidades.EdicionCurso;
import Logica.Entidades.Instituto;
import Logica.controladores.IControlador;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author xnahu
 */
public class IFConsultaEdicionCurso extends javax.swing.JInternalFrame {
    private IControlador controlador;
    /**
     * Creates new form IFConsultaEdicionCurso
     */
    public IFConsultaEdicionCurso(IControlador controlador) {
        initComponents();
         this.controlador = controlador;

    cmbInstituto.removeAllItems();
    cmbInstituto.addItem("Seleccione un instituto...");

    cmbCurso.removeAllItems();
    cmbCurso.addItem("Seleccione primero un instituto...");
    cmbCurso.setEnabled(false);

    cmbEdicion.removeAllItems();
    cmbEdicion.addItem("Seleccione primero un curso...");
    cmbEdicion.setEnabled(false);

    cargarInstitutos();
    }
    
    private void cargarInstitutos() {

    List<Instituto> institutos = controlador.listarInstitutos();

    for (Instituto instituto : institutos) {
        cmbInstituto.addItem(instituto.getNombre());
    }
}
    private void cargarCursosPorInstituto() {

    cmbCurso.removeAllItems();

    cmbEdicion.removeAllItems();
    cmbEdicion.addItem("Seleccione primero un curso...");
    cmbEdicion.setEnabled(false);

    if (cmbInstituto.getSelectedIndex() <= 0) {
        cmbCurso.addItem("Seleccione primero un instituto...");
        cmbCurso.setEnabled(false);
        return;
    }

    String nombreInstituto = cmbInstituto.getSelectedItem().toString();

    List<Curso> cursos =controlador.listarCursosPorInstituto(nombreInstituto);

    if (cursos.isEmpty()) {
        cmbCurso.addItem("No hay cursos disponibles");
        cmbCurso.setEnabled(false);
        return;
    }

    cmbCurso.addItem("Seleccione un curso...");

    for (Curso curso : cursos) {
        cmbCurso.addItem(curso.getNombre());
    }

    cmbCurso.setEnabled(true);
}
    private void cargarEdicionesPorCurso() {

    cmbEdicion.removeAllItems();

    if (!cmbCurso.isEnabled() || cmbCurso.getSelectedIndex() <= 0) {
        cmbEdicion.addItem("Seleccione primero un curso...");
        cmbEdicion.setEnabled(false);
        return;
    }

    String nombreCurso = cmbCurso.getSelectedItem().toString();

    List<EdicionCurso> ediciones =
            controlador.listarEdicionesPorCurso(nombreCurso);

    if (ediciones.isEmpty()) {
        cmbEdicion.addItem("No hay ediciones disponibles");
        cmbEdicion.setEnabled(false);
        return;
    }

    cmbEdicion.addItem("Seleccione una edición...");

    for (EdicionCurso edicion : ediciones) {
        cmbEdicion.addItem(edicion.getNombre());
    }

    cmbEdicion.setEnabled(true);
}
   
    private void limpiarDatosEdicion() {

    txtNombre.setText("");
    txtFechaInicio.setText("");
    txtFechaFin.setText("");
    txtCupo.setText("");
    txtFechaPublicacion.setText("");

    lstDocentes.setModel(new DefaultListModel<>());
}
    
    private void mostrarDatosEdicion() {

    if (!cmbEdicion.isEnabled() || cmbEdicion.getSelectedIndex() <= 0) {
        limpiarDatosEdicion();
        return;
    }

    String nombreEdicion = cmbEdicion.getSelectedItem().toString();

    DetalleEdicionCurso detalle =
            controlador.consultarEdicion(nombreEdicion);

    if (detalle == null) {
        limpiarDatosEdicion();
        return;
    }

    txtNombre.setText(detalle.getNombre());
    txtFechaInicio.setText(detalle.getFechaInicio().toString());
    txtFechaFin.setText(detalle.getFechaFin().toString());

    if (detalle.getCupo() == null) {
        txtCupo.setText("Sin límite");
    } else {
        txtCupo.setText(detalle.getCupo().toString());
    }

    txtFechaPublicacion.setText(
            detalle.getFechaPublicacion().toString()
    );

    DefaultListModel<String> modelo = new DefaultListModel<>();

    for (String docente : detalle.getDocentes()) {
        modelo.addElement(docente);
    }

    lstDocentes.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbInstituto = new javax.swing.JComboBox<>();
        cmbCurso = new javax.swing.JComboBox<>();
        cmbEdicion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        txtCupo = new javax.swing.JTextField();
        txtFechaPublicacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDocentes = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        cmbInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInstituto.addActionListener(this::cmbInstitutoActionPerformed);

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCurso.addActionListener(this::cmbCursoActionPerformed);

        cmbEdicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEdicion.addActionListener(this::cmbEdicionActionPerformed);

        jLabel1.setText("Instituto: ");

        jLabel2.setText("Curso: ");

        jLabel3.setText("Edición: ");

        jLabel4.setText("DATOS DE LA EDICIÓN");

        txtNombre.setEditable(false);
        txtNombre.setText("jTextField1");
        txtNombre.setPreferredSize(new java.awt.Dimension(220, 26));

        txtFechaInicio.setEditable(false);
        txtFechaInicio.setText("jTextField2");
        txtFechaInicio.setPreferredSize(new java.awt.Dimension(120, 26));

        txtFechaFin.setEditable(false);
        txtFechaFin.setText("jTextField3");
        txtFechaFin.setPreferredSize(new java.awt.Dimension(120, 26));

        txtCupo.setEditable(false);
        txtCupo.setText("jTextField4");
        txtCupo.setPreferredSize(new java.awt.Dimension(80, 26));

        txtFechaPublicacion.setEditable(false);
        txtFechaPublicacion.setText("jTextField5");
        txtFechaPublicacion.setPreferredSize(new java.awt.Dimension(120, 26));

        jLabel5.setText("DOCENTES: ");

        lstDocentes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstDocentes);

        jLabel6.setText("Nombre:");

        jLabel7.setText("Fecha de inicio:");

        jLabel8.setText("Fecha de fin:");

        jLabel9.setText("Cupo:");

        jLabel10.setText("Fecha publicación:");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstitutoActionPerformed
         cargarCursosPorInstituto();
    }//GEN-LAST:event_cmbInstitutoActionPerformed

    private void cmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoActionPerformed
            cargarEdicionesPorCurso();

    }//GEN-LAST:event_cmbCursoActionPerformed

    private void cmbEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEdicionActionPerformed
        mostrarDatosEdicion();
    }//GEN-LAST:event_cmbEdicionActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose(); 
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbEdicion;
    private javax.swing.JComboBox<String> cmbInstituto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstDocentes;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaPublicacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
