/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Logica.DTO.DetalleCurso;
import Logica.DTO.DetalleEdicionCurso;
import Logica.DTO.DetalleProgramaFormacion;
import Logica.DTO.CursoResumen;
import Logica.Entidades.Curso;
import Logica.Entidades.Instituto;
import Logica.controladores.Fabrica;
import Logica.controladores.IControlador;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.List;
/**
 *
 * @author Usuario
 */
public class IFConsultaCurso extends javax.swing.JInternalFrame {

     private final IControlador control;
    /**
     * Creates new form IFConsultaCurso
     */
    public IFConsultaCurso() {
        this.control = Fabrica.getInstance().getIControlador();
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consulta de Curso");
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        cargarInstitutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblInsitututo = new javax.swing.JLabel();
        lblInstituto2 = new javax.swing.JLabel();
        cbInstitutos = new javax.swing.JComboBox<>();
        lblInstituto = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnVerDetalleEdicion = new javax.swing.JButton();
        btnVerDetallePrograma = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usersSeparator7 = new javax.swing.JSeparator();
        usersSeparator8 = new javax.swing.JSeparator();
        usersSeparator9 = new javax.swing.JSeparator();
        usersSeparator10 = new javax.swing.JSeparator();
        usersSeparator11 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(910, 910));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 71, 75));

        lblInsitututo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInsitututo.setForeground(new java.awt.Color(206, 206, 206));
        lblInsitututo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsitututoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInsitututoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInsitututoMouseExited(evt);
            }
        });

        lblInstituto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInstituto2.setForeground(new java.awt.Color(255, 255, 255));
        lblInstituto2.setText("Consulta Curso");
        lblInstituto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstituto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInstituto2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInstituto2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInsitututo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInstituto2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(727, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstituto2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsitututo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        cbInstitutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbInstitutos.setBorder(null);
        cbInstitutos.addActionListener(this::cbInstitutosActionPerformed);
        getContentPane().add(cbInstitutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 410, 30));

        lblInstituto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInstituto.setForeground(new java.awt.Color(35, 71, 75));
        lblInstituto.setText("Instituto");
        getContentPane().add(lblInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        cbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCursos.setBorder(null);
        cbCursos.addActionListener(this::cbCursosActionPerformed);
        getContentPane().add(cbCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 410, 30));

        lblCurso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(35, 71, 75));
        lblCurso.setText("Curso");
        getContentPane().add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 71, 75));
        jLabel3.setText("Detalle Curso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 470, 110));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 210, 120));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 230, 120));

        btnVerDetalleEdicion.setBackground(new java.awt.Color(35, 71, 75));
        btnVerDetalleEdicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerDetalleEdicion.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalleEdicion.setText("Ver Detalle Edicion");
        btnVerDetalleEdicion.addActionListener(this::btnVerDetalleEdicionActionPerformed);
        getContentPane().add(btnVerDetalleEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 160, 40));

        btnVerDetallePrograma.setBackground(new java.awt.Color(35, 71, 75));
        btnVerDetallePrograma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerDetallePrograma.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetallePrograma.setText("Ver Detalle Programa");
        btnVerDetallePrograma.addActionListener(this::btnVerDetalleProgramaActionPerformed);
        getContentPane().add(btnVerDetallePrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 170, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 71, 75));
        jLabel1.setText("Programas de Formacion Asociados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 71, 75));
        jLabel2.setText("Ediciones asociadas al Curso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        usersSeparator7.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 230, 10));

        usersSeparator8.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 410, 10));

        usersSeparator9.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 410, 10));

        usersSeparator10.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 470, 10));

        usersSeparator11.setForeground(new java.awt.Color(35, 71, 75));
        getContentPane().add(usersSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 210, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbInstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInstitutosActionPerformed
         cbCursos.removeAllItems();
        limpiarDetalles();
        if (cbInstitutos.getSelectedIndex() > 0) {
            String instSeleccionado = (String) cbInstitutos.getSelectedItem();
            List<Curso> cursos = control.listarCursosPorInstituto(instSeleccionado);
            if (cursos != null && !cursos.isEmpty()) {
                cbCursos.addItem("Seleccione un curso...");
                for (Curso c : cursos) {
                    cbCursos.addItem(c.getNombre());
                }
            } else {
                cbCursos.addItem("No hay cursos para este instituto");
            }
        } else {
            cbCursos.addItem("Seleccione primero un instituto...");
        }
    }//GEN-LAST:event_cbInstitutosActionPerformed

    private void cbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursosActionPerformed
         if (cbCursos.getSelectedIndex() > 0) {
            String cursoSeleccionado = (String) cbCursos.getSelectedItem();
            DetalleCurso detalle = control.consultarCurso(cursoSeleccionado);

            if (detalle != null) {
                jTextArea1.setText(formatearDetalleCurso(detalle));
                jTextArea1.setCaretPosition(0);

                DefaultListModel<String> modelEd = new DefaultListModel<>();
                for (String ed : detalle.getEdiciones()) {
                    modelEd.addElement(ed);
                }
                jList1.setModel(modelEd);

                DefaultListModel<String> modelProg = new DefaultListModel<>();
                for (String prog : detalle.getProgramas()) {
                    modelProg.addElement(prog);
                }
                jList2.setModel(modelProg);
            } else {
                limpiarDetalles();
            }
        } else {
            limpiarDetalles();
        }
    }//GEN-LAST:event_cbCursosActionPerformed

    private void btnVerDetalleEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleEdicionActionPerformed
         String edicionSel = jList1.getSelectedValue();
        if (edicionSel == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una edición de la lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DetalleEdicionCurso detalleEd = control.consultarEdicion(edicionSel);
        if (detalleEd == null) {
            JOptionPane.showMessageDialog(this, "No se encontró la información de la edición.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Nombre de edición: ").append(detalleEd.getNombre()).append("\n");
        sb.append("Curso asociado: ").append(detalleEd.getCurso()).append("\n");
        sb.append("Fecha de inicio: ").append(detalleEd.getFechaInicio()).append("\n");
        sb.append("Fecha de fin: ").append(detalleEd.getFechaFin()).append("\n");
        sb.append("Cupo: ").append(detalleEd.getCupo() != null ? detalleEd.getCupo() : "Sin cupo definido").append("\n");
        sb.append("Fecha de publicación: ").append(detalleEd.getFechaPublicacion()).append("\n");
        sb.append("Docentes participantes:\n");
        if (detalleEd.getDocentes() == null || detalleEd.getDocentes().isEmpty()) {
            sb.append("  (sin docentes asignados)\n");
        } else {
            for (String doc : detalleEd.getDocentes()) {
                sb.append("  - ").append(doc).append("\n");
            }
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Consulta de Edición de Curso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerDetalleEdicionActionPerformed

    private void btnVerDetalleProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleProgramaActionPerformed
        String programaSel = jList2.getSelectedValue();
        if (programaSel == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un programa de formación de la lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DetalleProgramaFormacion detalleProg = control.consultarPrograma(programaSel);
        if (detalleProg == null) {
            JOptionPane.showMessageDialog(this, "No se encontró información para el programa de formación.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Nombre de programa: ").append(detalleProg.getNombre()).append("\n");
        sb.append("Descripción: ").append(detalleProg.getDescripcion()).append("\n");
        sb.append("Período de vigencia: ").append(detalleProg.getFechaInicio()).append(" a ").append(detalleProg.getFechaFin()).append("\n");
        sb.append("Fecha de alta: ").append(detalleProg.getFechaAlta()).append("\n");
        sb.append("Cursos que lo integran:\n");
        if (detalleProg.getCursos() == null || detalleProg.getCursos().isEmpty()) {
            sb.append("  (sin cursos asociados)\n");
        } else {
            for (CursoResumen c : detalleProg.getCursos()) {
                sb.append("  - ").append(c.toString()).append("\n");
            }
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Consulta de Programa de Formación", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerDetalleProgramaActionPerformed

    private void lblInsitututoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsitututoMouseClicked

    }//GEN-LAST:event_lblInsitututoMouseClicked

    private void lblInsitututoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsitututoMouseEntered

    }//GEN-LAST:event_lblInsitututoMouseEntered

    private void lblInsitututoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsitututoMouseExited

    }//GEN-LAST:event_lblInsitututoMouseExited

    private void lblInstituto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstituto2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInstituto2MouseClicked

    private void lblInstituto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstituto2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInstituto2MouseEntered

    private void lblInstituto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstituto2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInstituto2MouseExited

    private void limpiarDetalles() {
        jTextArea1.setText("");
        jList1.setModel(new DefaultListModel<>());
        jList2.setModel(new DefaultListModel<>());
    }
    
    private String formatearDetalleCurso(DetalleCurso detalle) {
        StringBuilder sb = new StringBuilder();
        sb.append("Nombre: ").append(detalle.getNombre()).append("\n");
        sb.append("Descripción: ").append(detalle.getDescripcion()).append("\n");
        sb.append("Duración: ").append(detalle.getDuracion()).append(" meses\n");
        sb.append("Horas: ").append(detalle.getCantidadHoras()).append("\n");
        sb.append("Créditos: ").append(detalle.getCreditos()).append("\n");
        sb.append("URL: ").append(detalle.getUrl()).append("\n");
        sb.append("Fecha de alta: ").append(detalle.getFechaAlta()).append("\n");
        sb.append("Instituto: ").append(detalle.getInstituto()).append("\n");

        sb.append("Previas: ");
        if (detalle.getPrevias() == null || detalle.getPrevias().isEmpty()) {
            sb.append("Ninguna\n");
        } else {
            sb.append(String.join(", ", detalle.getPrevias())).append("\n");
        }

        return sb.toString();
    }
    
     private void cargarInstitutos() {
        cbInstitutos.removeAllItems();
        cbInstitutos.addItem("Seleccione un instituto...");
        List<Instituto> institutos = control.listarInstitutos();
        for (Instituto inst : institutos) {
            cbInstitutos.addItem(inst.getNombre());
        }
        cbCursos.removeAllItems();
        cbCursos.addItem("Seleccione primero un instituto...");
        limpiarDetalles();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerDetalleEdicion;
    private javax.swing.JButton btnVerDetallePrograma;
    private javax.swing.JComboBox<String> cbCursos;
    private javax.swing.JComboBox<String> cbInstitutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblInsitututo;
    private javax.swing.JLabel lblInstituto;
    private javax.swing.JLabel lblInstituto2;
    private javax.swing.JSeparator usersSeparator10;
    private javax.swing.JSeparator usersSeparator11;
    private javax.swing.JSeparator usersSeparator7;
    private javax.swing.JSeparator usersSeparator8;
    private javax.swing.JSeparator usersSeparator9;
    // End of variables declaration//GEN-END:variables
}
