/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author samio
 */
public class JFMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFMain.class.getName());

    /**
     * Creates new form JFMain
     */
    public JFMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mntmAltaUsuario = new javax.swing.JMenuItem();
        mntmAltaCurso = new javax.swing.JMenuItem();
        mntmAltaEdicionCurso = new javax.swing.JMenuItem();
        mntmInscripcionEdicionCurso = new javax.swing.JMenuItem();
        mntmCrearProgramaFormacion = new javax.swing.JMenuItem();
        mntmAgregarCursoProgramaFormacion = new javax.swing.JMenuItem();
        mntmAltaInstituto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mntmConsultaUsuario = new javax.swing.JMenuItem();
        mntmConsultaCurso = new javax.swing.JMenuItem();
        mntmConsultaEdicionCurso = new javax.swing.JMenuItem();
        mntmConsultaProgramaFormacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mntmModificarDatosUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jMenu1.setText("Registros");

        mntmAltaUsuario.setText("Alta de Usuario");
        mntmAltaUsuario.addActionListener(this::mntmAltaUsuarioActionPerformed);
        jMenu1.add(mntmAltaUsuario);

        mntmAltaCurso.setText("Alta de Curso");
        mntmAltaCurso.addActionListener(this::mntmAltaCursoActionPerformed);
        jMenu1.add(mntmAltaCurso);

        mntmAltaEdicionCurso.setText("Alta de Edicion de Curso");
        jMenu1.add(mntmAltaEdicionCurso);

        mntmInscripcionEdicionCurso.setText("Inscripcion a Edicion de Curso");
        jMenu1.add(mntmInscripcionEdicionCurso);

        mntmCrearProgramaFormacion.setText("Crear Programa de Formacion");
        jMenu1.add(mntmCrearProgramaFormacion);

        mntmAgregarCursoProgramaFormacion.setText("Agregar Curso a Programa de Formacion");
        jMenu1.add(mntmAgregarCursoProgramaFormacion);

        mntmAltaInstituto.setText("Alta de Instituto");
        mntmAltaInstituto.addActionListener(this::mntmAltaInstitutoActionPerformed);
        jMenu1.add(mntmAltaInstituto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        mntmConsultaUsuario.setText("Consulta de Usuario");
        jMenu2.add(mntmConsultaUsuario);

        mntmConsultaCurso.setText("Consulta de Curso");
        jMenu2.add(mntmConsultaCurso);

        mntmConsultaEdicionCurso.setText("Consulta de Edicion de Curso");
        jMenu2.add(mntmConsultaEdicionCurso);

        mntmConsultaProgramaFormacion.setText("Consulta de Programa de Formacion");
        jMenu2.add(mntmConsultaProgramaFormacion);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Modificaciones");

        mntmModificarDatosUsuario.setText("Modificar Datos de Usuario");
        jMenu3.add(mntmModificarDatosUsuario);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntmAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmAltaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntmAltaUsuarioActionPerformed

    private void mntmAltaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmAltaCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mntmAltaCursoActionPerformed

    private void mntmAltaInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmAltaInstitutoActionPerformed
       AltaInstitutoInternalFrame frame = new AltaInstitutoInternalFrame();
    jDesktopPane1.add(frame);
    frame.setVisible(true);
    try {
        frame.setSelected(true);
    } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_mntmAltaInstitutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mntmAgregarCursoProgramaFormacion;
    private javax.swing.JMenuItem mntmAltaCurso;
    private javax.swing.JMenuItem mntmAltaEdicionCurso;
    private javax.swing.JMenuItem mntmAltaInstituto;
    private javax.swing.JMenuItem mntmAltaUsuario;
    private javax.swing.JMenuItem mntmConsultaCurso;
    private javax.swing.JMenuItem mntmConsultaEdicionCurso;
    private javax.swing.JMenuItem mntmConsultaProgramaFormacion;
    private javax.swing.JMenuItem mntmConsultaUsuario;
    private javax.swing.JMenuItem mntmCrearProgramaFormacion;
    private javax.swing.JMenuItem mntmInscripcionEdicionCurso;
    private javax.swing.JMenuItem mntmModificarDatosUsuario;
    // End of variables declaration//GEN-END:variables
}
