#!/bin/bash
set -e

mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS ${MARIADB_DATABASE};
    GRANT ALL PRIVILEGES ON ${MARIADB_DATABASE}.* TO '${MARIADB_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS edext_web;
    GRANT ALL PRIVILEGES ON edext_web.* TO '${MARIADB_USER}'@'%';
EOSQL
